app:
  name: "Legal Contract Analysis Bot"
  version: "1.0.0"
  debug: true

interface:
  type: "web"
  web:
    host: "0.0.0.0"
    port: 8000
    reload: true

storage:
  type: "local"
  local:
    base_path: "./data"

llm:
  provider: "anthropic"
  model: "claude-3-5-sonnet-latest"
  temperature: 0.1
  max_tokens: 4000

document_processing:
  max_file_size_mb: 50
  supported_formats: ["pdf", "docx", "txt"]
  temp_upload_path: "./data/uploads"

risk_assessment:
  default_rules_file: "./config/risk-rules.json"
  high_risk_threshold: 7
  medium_risk_threshold: 4