app:
  name: "Legal Contract Analysis Bot"
  version: "1.0.0"
  debug: true

interface:
  type: "web"
  web:
    host: "0.0.0.0"
    port: 8000
    reload: true

storage:
  # type: "local"
  # local:
  #   base_path: "./data"

llm:
  provider: "google_gemini"
  model: "gemini-2.5-pro"
  temperature: 1

document_processing:
  knowledge_base_path: "./data/knowledge_base"
  escalation_rules_file: "./config/escalation-rules.txt"

